name: Build and publish Docker images

on:
  push:
    branches:
      - devel
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Log in to registry
        run: >-
          echo "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: publish devel
        if: github.ref_type == 'branch'
        run: make _publish

      - name: publish tagged
        if: github.ref_type == 'tag'
        run: TAG=${${{ github.refname }}#v*} make _publish
